
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[243] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   51,   49,   48,   48,   42,   44,   45,    7,
        7,   43,   32,   31,   42,   49,   46,   49,   47,   49,
       49,   49,   49,   49,   49,   49,   49,    4,   50,    4,
        4,    4,    9,    9,   12,   12,   50,   15,   14,   15,
       18,   18,   18,   18,   48,   33,   42,    0,    0,    0,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    8,
        0,    0,   34,    0,   23,    0,   42,   42,   42,   42,
       42,   42,    0,    0,    0,    0,    0,    6,    6,    6,
        2,    0,    0,    5,    0,    9,    0,   12,   12,   12,

        0,   14,   18,    0,    0,    0,    0,   27,   28,   10,
       13,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   42,   42,   42,    1,    6,    6,    2,    0,
        3,   12,   12,   12,   12,   12,   11,    0,   16,   30,
       24,   29,   42,   42,   42,    0,   42,   35,    0,    0,
        0,    0,    0,    2,   12,   12,   12,   17,    0,    0,
        0,    0,   42,    0,   42,   42,   42,   42,   42,   12,
       12,   12,   25,   42,   37,    0,    0,   42,    0,    0,
        0,    0,    0,   12,   12,    0,    0,   42,   42,    0,
       19,   42,   42,   42,    0,   12,   12,   26,   21,    0,

        0,    0,    0,    0,    0,   42,   12,   12,   42,    0,
       42,    0,   42,   22,    0,   12,   12,    0,   42,    0,
       40,    0,    0,   12,   42,    0,   39,    0,   36,    0,
       42,   42,    0,    0,    0,   42,    0,   20,    0,   38,
       41,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    6,    1,    7,
        8,    1,    1,    1,    1,    1,    1,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,   11,   12,
        1,   13,    1,   14,   15,   16,   15,   15,   17,   15,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   18,    1,
        1,    1,    1,    1,    1,    1,   15,   15,   15,   15,

       15,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   19,    1,    1,    1,    1,   20,
        1,    1,   21,   22,   23,    1,    1,   24,   25,   26,
        1,    1,   27,   28,    1,    1,    1,   29,   30,    1,
        1,    1,    1,   31,   32,   33,   34,   35,    1,    1,
        1,   36,   37,   38,    1,   39,   40,   41,    1,    1,
       42,   43,    1,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    1,   53,    1,   54,   55,    1,    1,    1,
       56,   57,    1,   58,   59,   60,    1,    1,    1,   61,
       62,    1,    1,   63,   64,   65,   66,    1,    1,    1,

        1,    1,   67,    1,    1,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[248] =
    {   0,
        0,   68,   16,   24,   15,   19,   25,   26,   15,   36,
       38,   43,  450, 1392,   47,   48,   81, 1392, 1392, 1392,
        6, 1392,  384,  381,   91,   96, 1392,  417, 1392,  125,
      152,   68,  161,    9,  383,  369,   32, 1392, 1392,  185,
      374,  394, 1392,  112,   84,   89,  396, 1392, 1392,  362,
     1392, 1392,  357,  381,   96,  165,  178,  209,  236,  157,
      245,   17,  332,  310,  115,  100,  314,  305,  322, 1392,
      309,  309, 1392,  261,  260,  258,  262,  272,  281,  290,
      299,  308,  275,  181,  248,  250,   86, 1392,  293,  302,
      370,  239,  253, 1392,  234,  373,    8,  193,  159,  220,

      244, 1392, 1392,  220,  186,  356,  174, 1392, 1392, 1392,
     1392,  178,  162,  155,  149,  352,  372,  373,  255,  392,
      408,  396,  411,  422,  432, 1392,  494,  497, 1392,  126,
     1392,  281,  221,  451,  232,  233, 1392,  147, 1392, 1392,
       90, 1392,  456,  502,  521,  100,  530,  539,  493,  498,
      585,  588,  592, 1392,  538,  245,  280, 1392,   98,  599,
      613,  533,  614,  639,  637,  653,  662,  681,  727,  297,
      302,  398,   77,  746,  755,  542,  709,  764,  737,  807,
      806,  727,   70,  556,  558,   81,  824,  830,  844,  624,
      864,  873,  909,  938,   83,  608,  619, 1392,  947,  990,

      664,  767,  665,  913,  991, 1014,  637,  692, 1024,  506,
     1033,  950, 1044, 1053,  685,  694,   99,  937, 1062, 1108,
     1129,  751,   46,   68, 1138, 1108, 1157, 1141, 1169,  813,
     1203, 1234, 1206,  862, 1228, 1245, 1246, 1274, 1299, 1312,
     1321, 1392,   60,   41,    3,    1,    0
    } ;

static const flex_int16_t yy_def[248] =
    {   0,
      243,  243,  244,  244,  245,  245,  245,  245,  246,  246,
      247,  247,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,    0,  242,  242,  242,  242,  242
    } ;

static const flex_int16_t yy_nxt[1463] =
    {   0,
       51,   48,   15,   39,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   66,   66,   26,   49,   39,  132,
       27,   28,   29,   43,   44,  133,   39,   43,   44,   44,
       44,   44,   40,   44,   44,   44,   45,   45,   49,   52,
       40,   38,   46,   46,   52,   57,   57,   47,   47,   55,
       55,   55,   55,   57,   57,   84,   52,   85,   86,   87,
       14,   52,   30,   31,   32,   33,   34,   35,   36,   37,
       15,   97,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   50,   41,   26,   42,   56,   97,   27,   28,
       29,   41,   97,   42,   57,   98,   57,  229,   55,   57,

       55,   99,   97,   50,   57,   53,  100,   54,   66,   66,
       53,   69,   54,   57,   57,   70,   57,   57,   57,   57,
       96,   96,   81,  206,  198,   57,   96,   96,   96,  195,
       30,   31,   32,   33,   34,   35,   36,   37,  106,  186,
      107,  173,   87,   58,   59,   60,   61,   62,   63,   64,
       65,  163,  159,   58,   59,   60,   61,   62,   63,   64,
       65,   71,   97,  158,  154,   72,   74,   57,   75,   57,
       57,   76,   57,   77,   78,   57,  135,   79,   57,   57,
       57,   57,   57,   57,   57,   82,   82,   57,   57,   57,
       57,   57,   80,   88,   89,  142,   97,   57,  141,   90,

       90,   91,   57,   57,  134,   57,   57,   57,  140,   57,
       99,   57,   57,  139,   57,   57,   57,   57,  124,   57,
       57,   57,   57,   97,   97,   57,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   97,   97,  136,  100,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   97,  156,
      157,   57,   92,   57,   93,  138,   57,   57,   57,   57,
      137,   57,  171,   57,   57,   57,   57,   57,   57,   82,
       82,   57,  131,   57,   57,   57,   57,   57,  106,  130,
      146,   57,   87,   97,   97,   57,   57,  129,  126,   57,
       57,   57,   98,   57,   57,   57,   57,  172,   99,  125,

       97,  127,  127,   57,   57,   97,   57,  128,  128,  128,
      128,  128,   57,   57,   99,  123,  128,  128,  128,  184,
      115,   57,  114,  113,   58,   59,  116,   61,   62,   63,
       64,   65,  112,  111,   58,  117,   60,   61,   62,   63,
       64,   65,  110,   58,  118,   60,   61,   62,   63,   64,
      119,  109,  120,   59,   60,   61,   62,   63,   64,   65,
      108,  121,   59,   60,   61,   62,   63,   64,  122,  105,
       58,   59,   60,   61,   62,   63,   64,   65,  128,  128,
       57,   96,   96,   57,  128,  128,  128,   96,   96,   96,
       57,   57,   57,   57,   57,   57,   57,  143,   57,   57,

      145,   97,   57,   57,  104,  103,   57,  144,   57,   57,
      102,  101,   57,   57,   57,  185,   57,   57,   57,  149,
       95,  107,   94,   87,   57,   57,   57,   57,   83,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   73,   57,
       57,   57,   57,   68,  147,   57,   67,   57,   57,  242,
       57,   57,   57,  242,   97,   57,   57,  148,   57,  242,
       57,   57,  155,   57,   57,  242,  242,   57,   99,   57,
      242,  242,  242,  150,   59,   60,  151,   62,   63,   64,
       65,  242,  242,  242,   58,  152,   60,   61,   62,   63,
       64,   65,  242,  242,   58,   59,   60,  153,   62,   63,

       64,   65,  127,  127,  242,  128,  128,   57,  128,  128,
      128,  128,  128,  128,  242,   57,  242,  242,   58,  160,
       60,   61,   62,   63,   64,   65,   57,   57,   57,  165,
       57,   57,   57,   57,   57,   57,   57,  219,   57,   57,
       57,   97,   57,   57,   57,   57,  166,   57,   57,  170,
       57,   57,   57,   57,   57,   99,  176,   57,  107,   97,
       87,   97,  242,  242,  161,   59,   60,   61,   62,   63,
       64,   65,  242,  196,  242,  197,   57,   57,  188,   57,
       57,   57,   57,   58,   59,   60,   61,   62,   63,   64,
      162,  242,   58,   59,  164,   61,   62,   63,   64,   65,

       57,   58,   59,   60,   61,   62,   63,   64,   65,   82,
       82,   97,  242,   57,   57,   57,  169,   82,   57,   57,
       57,   57,   97,  168,  242,  207,  174,   57,   57,   57,
      167,   57,  242,   57,   57,  242,  208,   57,   57,   57,
       97,   57,   57,  242,   57,   57,   57,  202,   57,  107,
       57,   87,   57,   57,  216,   57,   57,   57,   57,   57,
       57,   57,   57,   57,  242,  175,   57,   57,   57,   57,
       57,  242,   57,  242,  242,   57,   58,   59,   60,  177,
       62,   63,   64,   65,   57,   57,   57,  106,  212,  107,
      107,  210,   87,  178,   57,   97,   57,   97,  242,   58,

       59,   60,  179,   62,   63,   64,   65,  242,  106,  217,
      223,  224,   87,  242,  242,   58,  180,   60,   61,   62,
       63,   64,   65,  242,  181,   59,   60,   61,   62,   63,
       64,   65,   57,   82,   82,  242,  242,   57,   57,  242,
       57,  242,  242,   58,   59,  182,   61,   62,   63,   64,
       65,   57,  242,  242,  189,   57,  242,  242,   57,   57,
       57,   82,   82,  242,  242,   57,   57,  242,   57,   57,
       57,  242,   57,   57,  228,  242,  107,   57,   87,  242,
      242,  194,  191,   57,   57,  242,  242,  242,  242,   58,
       59,   60,   61,   62,   63,  183,   65,  242,   57,  242,

      242,   57,   57,  211,   57,   57,   57,   57,  187,   59,
       60,   61,   62,   63,   64,   65,  242,   58,   59,   60,
       61,   62,   63,   64,   65,   57,   58,   59,   60,   61,
       62,   63,   64,  190,  192,   57,  233,   57,  107,  242,
       87,  242,   57,   57,  242,  242,  242,   57,   57,   57,
       57,  242,   57,   57,   57,   57,   57,   57,  193,  242,
       57,   57,   57,  242,   57,   57,   57,   57,   57,   57,
      242,   57,   57,   57,   57,  242,  199,   57,   57,   57,
       57,  242,  242,   57,  242,  237,   57,  107,  242,   87,
      242,  242,   58,  200,   60,   61,   62,   63,   64,   65,

      242,  242,  242,  242,  242,  242,   58,   59,   60,   61,
       62,   63,   64,  201,   57,  242,  242,  242,  242,  242,
      242,  242,   57,  242,  242,  242,   58,   59,   60,   61,
       62,   63,   64,   65,  242,   58,   59,   60,   61,   62,
       63,   64,  203,   57,   57,  242,  242,  242,  242,  242,
      242,   57,   57,  242,  242,  242,  242,  242,   57,   57,
       57,  242,  242,  242,  242,  242,  242,  213,   57,  242,
       57,   58,   59,  204,   61,   62,   63,   64,   65,  242,
      242,  242,   57,   57,   57,   57,  221,   57,   57,   57,
       57,  225,  242,  242,   57,  242,  242,  242,  242,  242,

       58,  205,   60,   61,   62,   63,   64,   65,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   57,   57,   57,
      209,  214,  242,  242,  242,   57,   57,   57,  242,   57,
       57,   57,  242,  242,  242,   57,   57,   57,   57,  242,
      242,  242,  242,   57,   57,  242,   57,   57,   57,   57,
       57,   57,  242,  242,  242,  242,  242,   57,   57,  242,
      242,  242,  242,  242,  242,  242,   57,   57,  242,  242,
      242,  242,  242,  242,  242,   57,   58,   59,   60,   61,
       62,   63,   64,  215,  242,  242,   58,   59,  218,   61,
       62,   63,   64,   65,  242,   58,   59,   60,  220,   62,

       63,   64,   65,  242,  242,  242,   58,   59,   60,   61,
       62,   63,   64,  222,  242,   58,   59,   60,   61,   62,
       63,   64,   65,  242,  226,   59,   60,   61,   62,   63,
       64,   65,   82,   82,   57,  242,   57,   57,  242,  242,
      242,  242,   57,   57,  242,  242,  242,  242,  242,  242,
       57,   57,   57,  227,   57,   57,   57,   57,   57,  242,
      231,  242,   57,   57,   57,  242,  242,   57,  242,   57,
       57,  242,  242,  242,   57,   57,   57,  232,   57,   57,
       57,   57,   57,  242,  242,  242,  242,  242,  242,  242,
      242,   58,   59,   60,   61,   62,   63,   64,   65,   57,

       58,   59,   60,   61,   62,   63,   64,  230,   57,  242,
      242,  242,  242,  242,  242,  242,   57,  242,  242,   58,
       59,   60,   61,   62,   63,   64,   65,  242,  242,  242,
      242,   58,   59,   60,   61,   62,   63,   64,   65,   57,
       57,   57,  236,   57,   57,   57,   57,   57,  242,  242,
       57,  242,   82,   82,  242,  242,  238,   57,   57,  242,
      242,  242,  242,  242,   57,   58,   59,   60,   61,   62,
       63,   64,  234,   57,   57,  242,  242,  242,  242,   57,
       57,   57,  240,   57,   57,   57,   57,   57,  242,   57,
      242,  242,  242,  242,  242,  242,   58,   59,   60,  235,

       62,   63,   64,   65,   57,  242,  242,   58,   59,   60,
      239,   62,   63,   64,   65,  242,  242,   57,  242,  242,
      242,  242,  242,   82,   82,   57,   57,   57,   57,  242,
      242,  242,  242,  242,   57,  242,   58,   59,   60,   61,
       62,   63,   64,   65,  241,   57,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
       57,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,   58,   59,   60,   61,   62,   63,
       64,   65,  242,   58,   59,   60,   61,   62,   63,   64,
       65,   13,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242
    } ;

static const flex_int16_t yy_chk[1463] =
    {   0,
      247,  246,    1,  245,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   21,   21,    1,    9,    3,   97,
        1,    1,    1,    5,    5,   97,    4,    6,    6,    5,
        5,    5,    3,    6,    6,    6,    7,    8,   10,   11,
        4,  244,    7,    8,   12,   34,   34,    7,    8,   15,
       16,   15,   16,   62,   62,   37,   11,   37,   37,   37,
      243,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        2,  224,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    9,    3,    2,    3,   17,   45,    2,    2,
        2,    4,   46,    4,   17,   45,   25,  223,   55,   32,

       55,   45,  217,   10,   25,   11,   46,   11,   66,   66,
       12,   26,   12,   32,   32,   26,   87,   87,   87,   87,
       44,   44,   32,  195,  186,   32,   44,   44,   44,  183,
        2,    2,    2,    2,    2,    2,    2,    2,   65,  173,
       65,  159,   65,   17,   17,   17,   17,   17,   17,   17,
       17,  146,  141,   25,   25,   25,   25,   25,   25,   25,
       25,   26,   99,  138,  130,   26,   30,   30,   30,   30,
       56,   30,   30,   30,   30,   30,   99,   30,   56,   31,
       30,   30,   31,   57,   30,   33,   33,   31,   60,   33,
       33,   57,   31,   40,   40,  115,   98,   31,  114,   40,

       40,   40,   60,   60,   98,   31,   33,   33,  113,   31,
       98,   60,   31,  112,   60,   84,   84,   84,   84,   84,
       84,   84,   33,  100,  133,  107,  105,   56,   56,   56,
       56,   56,   56,   56,   56,  135,  136,  100,  133,   84,
       57,   57,   57,   57,   57,   57,   57,   57,  156,  135,
      136,   58,   40,   58,   40,  104,   58,   58,   58,   58,
      101,   58,  156,   59,   58,   58,   59,   77,   58,   61,
       61,   59,   95,   61,   61,   77,   59,   78,  119,   93,
      119,   59,  119,  157,  132,   78,   79,   92,   86,   59,
       61,   61,  132,   59,   79,   80,   59,  157,  132,   85,

      170,   89,   89,   80,   81,  171,   61,   89,   89,   89,
       90,   90,   81,   82,  170,   83,   90,   90,   90,  171,
       76,   82,   75,   74,   77,   77,   77,   77,   77,   77,
       77,   77,   72,   71,   78,   78,   78,   78,   78,   78,
       78,   78,   69,   79,   79,   79,   79,   79,   79,   79,
       79,   68,   80,   80,   80,   80,   80,   80,   80,   80,
       67,   81,   81,   81,   81,   81,   81,   81,   81,   64,
       82,   82,   82,   82,   82,   82,   82,   82,   91,   91,
       63,   96,   96,  116,   91,   91,   91,   96,   96,   96,
      106,  106,  106,  106,  106,  106,  106,  116,  116,  117,

      118,  172,  117,  118,   54,   53,  116,  117,  118,  116,
       50,   47,  117,  118,  106,  172,  123,  117,  118,  122,
       42,  122,   41,  122,  123,  117,  118,  124,   36,  117,
      118,   35,  117,  118,  120,  124,  120,  125,   28,  120,
      120,  120,  120,   24,  120,  125,   23,  120,  120,   13,
      121,  120,  121,    0,  134,  121,  121,  121,  121,    0,
      121,  143,  134,  121,  121,    0,    0,  121,  134,  143,
        0,    0,    0,  123,  123,  123,  123,  123,  123,  123,
      123,    0,    0,    0,  124,  124,  124,  124,  124,  124,
      124,  124,    0,    0,  125,  125,  125,  125,  125,  125,

      125,  125,  127,  127,    0,  128,  128,  144,  127,  127,
      127,  128,  128,  128,    0,  144,    0,    0,  143,  143,
      143,  143,  143,  143,  143,  143,  145,  149,  149,  149,
      149,  149,  149,  149,  145,  147,  210,  210,  210,  210,
      150,  155,  150,  147,  148,  150,  150,  150,  150,  155,
      150,  149,  148,  150,  150,  155,  162,  150,  162,  184,
      162,  185,    0,    0,  144,  144,  144,  144,  144,  144,
      144,  144,    0,  184,    0,  185,  176,  176,  176,  176,
      176,  176,  176,  145,  145,  145,  145,  145,  145,  145,
      145,    0,  147,  147,  147,  147,  147,  147,  147,  147,

      176,  148,  148,  148,  148,  148,  148,  148,  148,  151,
      151,  196,    0,  151,  151,  152,  153,  153,  152,  163,
      153,  153,  197,  152,    0,  196,  160,  163,  152,  160,
      151,  151,    0,  152,  160,    0,  197,  153,  153,  160,
      207,  152,  165,    0,  160,  152,  151,  190,  152,  190,
      165,  190,  160,  153,  207,  161,  160,  161,  166,  160,
      161,  161,  161,  161,    0,  161,  166,  167,  161,  161,
      164,    0,  161,    0,    0,  167,  163,  163,  163,  163,
      163,  163,  163,  163,  164,  164,  168,  201,  203,  201,
      203,  201,  203,  164,  168,  208,  164,  216,    0,  165,

      165,  165,  165,  165,  165,  165,  165,    0,  215,  208,
      215,  216,  215,    0,    0,  166,  166,  166,  166,  166,
      166,  166,  166,    0,  167,  167,  167,  167,  167,  167,
      167,  167,  169,  177,  177,    0,    0,  177,  177,    0,
      169,    0,    0,  168,  168,  168,  168,  168,  168,  168,
      168,  174,    0,    0,  177,  177,    0,    0,  182,  174,
      175,  179,  179,    0,    0,  179,  179,    0,  175,  178,
      177,    0,  182,  182,  222,    0,  222,  178,  222,    0,
        0,  182,  179,  179,  182,    0,    0,    0,    0,  169,
      169,  169,  169,  169,  169,  169,  169,    0,  179,    0,

        0,  202,  202,  202,  202,  202,  202,  202,  174,  174,
      174,  174,  174,  174,  174,  174,    0,  175,  175,  175,
      175,  175,  175,  175,  175,  202,  178,  178,  178,  178,
      178,  178,  178,  178,  180,  188,  230,  180,  230,    0,
      230,    0,  180,  188,    0,    0,    0,  180,  181,  189,
      181,    0,  180,  181,  181,  181,  181,  189,  181,    0,
      180,  181,  181,    0,  180,  181,  187,  180,  187,  191,
        0,  187,  187,  187,  187,    0,  187,  191,  192,  187,
      187,    0,    0,  187,    0,  234,  192,  234,    0,  234,
        0,    0,  188,  188,  188,  188,  188,  188,  188,  188,

        0,    0,    0,    0,    0,    0,  189,  189,  189,  189,
      189,  189,  189,  189,  193,    0,    0,    0,    0,    0,
        0,    0,  193,    0,    0,    0,  191,  191,  191,  191,
      191,  191,  191,  191,    0,  192,  192,  192,  192,  192,
      192,  192,  192,  194,  204,    0,    0,    0,    0,    0,
        0,  194,  199,    0,    0,    0,    0,    0,  204,  204,
      199,    0,    0,    0,    0,    0,    0,  204,  218,    0,
      204,  193,  193,  193,  193,  193,  193,  193,  193,    0,
        0,    0,  218,  218,  212,  212,  212,  212,  212,  212,
      212,  218,    0,    0,  218,    0,    0,    0,    0,    0,

      194,  194,  194,  194,  194,  194,  194,  194,  212,  199,
      199,  199,  199,  199,  199,  199,  199,  200,  205,  206,
      200,  205,    0,    0,    0,  200,  205,  206,    0,  209,
      200,  205,    0,    0,    0,  200,  205,  209,  211,    0,
        0,    0,    0,  200,  205,    0,  211,  200,  205,  213,
      200,  205,    0,    0,    0,    0,    0,  213,  214,    0,
        0,    0,    0,    0,    0,    0,  214,  219,    0,    0,
        0,    0,    0,    0,    0,  219,  206,  206,  206,  206,
      206,  206,  206,  206,    0,    0,  209,  209,  209,  209,
      209,  209,  209,  209,    0,  211,  211,  211,  211,  211,

      211,  211,  211,    0,    0,    0,  213,  213,  213,  213,
      213,  213,  213,  213,    0,  214,  214,  214,  214,  214,
      214,  214,  214,    0,  219,  219,  219,  219,  219,  219,
      219,  219,  220,  220,  221,    0,  220,  220,    0,    0,
        0,    0,  221,  225,    0,    0,    0,    0,    0,    0,
      226,  225,  226,  220,  220,  226,  226,  226,  226,    0,
      226,    0,  227,  226,  226,    0,    0,  226,    0,  220,
      227,    0,    0,    0,  229,  228,  228,  228,  228,  228,
      228,  228,  229,    0,    0,    0,    0,    0,    0,    0,
        0,  221,  221,  221,  221,  221,  221,  221,  221,  228,

      225,  225,  225,  225,  225,  225,  225,  225,  231,    0,
        0,    0,    0,    0,    0,    0,  231,    0,    0,  227,
      227,  227,  227,  227,  227,  227,  227,    0,    0,    0,
        0,  229,  229,  229,  229,  229,  229,  229,  229,  232,
      233,  233,  233,  233,  233,  233,  233,  232,    0,    0,
      236,    0,  235,  235,    0,    0,  235,  235,  236,    0,
        0,    0,    0,    0,  233,  231,  231,  231,  231,  231,
      231,  231,  231,  235,  235,    0,    0,    0,    0,  238,
      237,  237,  237,  237,  237,  237,  237,  238,    0,  235,
        0,    0,    0,    0,    0,    0,  232,  232,  232,  232,

      232,  232,  232,  232,  237,    0,    0,  236,  236,  236,
      236,  236,  236,  236,  236,    0,    0,  240,    0,    0,
        0,    0,    0,  239,  239,  240,  241,  239,  239,    0,
        0,    0,    0,    0,  241,    0,  238,  238,  238,  238,
      238,  238,  238,  238,  239,  239,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      239,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  240,  240,  240,  240,  240,  240,
      240,  240,    0,  241,  241,  241,  241,  241,  241,  241,
      241,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[50] =
    {   0,
      112,  113,  114,  115,  116,  117,  120,  122,  123,  125,
      126,  127,  130,  131,  132,  134,  135,  136,  138,  139,
      140,  141,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  158,  159,  160,  161,  162,  163,
      164,  167,  170,  171,  172,  173,  174,  176,  178
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

#include "parser.tab.h"

#define UTF8_EURO_LEN 3 


void addstr(char ch);
int babylonian_to_decimal(char* str);

char* str_buf;


// Initialize the string buffer before any rules are executed
void init_str_buf();
#define YY_USER_INIT init_str_buf();


#line 958 "lex.yy.c"
#define YY_NO_INPUT 1
/* Datatypes */
/* Operators */
/* Keywords */
/* Special */

#line 965 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define HEX 2
#define BABYLONIAN 3
#define LINECOMMENT 4
#define BLOCKCOMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals ( void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT
    
#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 109 "lexer.l"



#line 1252 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 243 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1392 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 50 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 50 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 51 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 112 "lexer.l"
{ BEGIN(STRING); *str_buf = '\0'; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 113 "lexer.l"
{for (int i = UTF8_EURO_LEN; i < yyleng; i++){ addstr(yytext[i]);} } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 114 "lexer.l"
{ BEGIN(INITIAL); yylval.str = strdup(str_buf); return STR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "lexer.l"
{ addstr(*yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "lexer.l"
{ addstr('\n'); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 117 "lexer.l"
{ addstr(atoi(yytext + UTF8_EURO_LEN)); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 120 "lexer.l"
{ yylval.num = atoi(yytext); return NUM; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 122 "lexer.l"
{ BEGIN(HEX); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "lexer.l"
{ BEGIN(INITIAL); yylval.num = strtol(yytext, NULL, 16); return NUM; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 125 "lexer.l"
{ BEGIN(BABYLONIAN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 126 "lexer.l"
{BEGIN(INITIAL); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 127 "lexer.l"
{ yylval.num = babylonian_to_decimal(yytext); return NUM; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 130 "lexer.l"
{ BEGIN(LINECOMMENT);  *str_buf = '\0';}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 131 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 132 "lexer.l"
{ addstr(*yytext); /* addstr could be removed here to completely ignore comments */ }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "lexer.l"
{ BEGIN(BLOCKCOMMENT); *str_buf = '\0'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 136 "lexer.l"
{ addstr(*yytext); /* addstr could be removed here to completly ignore comments */ }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "lexer.l"
{ yylval.type = strdup(yytext); return TYPE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 139 "lexer.l"
{ yylval.type = strdup(yytext); return TYPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 140 "lexer.l"
{ yylval.type = strdup(yytext); return TYPE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 141 "lexer.l"
{ yylval.type = strdup(yytext); return TYPE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return PLUS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return MINUS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return MULT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return DIV; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return LE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return GE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return EQ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return NE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return GT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return LT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return AND; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return OR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return IF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return ELSE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return FOR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return RETURN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return PRINT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return SCAN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 164 "lexer.l"
{ yylval.num = rand(); return RAND_INT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 167 "lexer.l"
{ yylval.id = strdup(yytext); return ID; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return SEMICOLON; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return ROUND_OPEN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return ROUND_CLOSE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return CURLY_OPEN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return CURLY_CLOSE; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 176 "lexer.l"
{ } // Ignore delimiter
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return *yytext; } // Return any other character
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "lexer.l"
ECHO;
	YY_BREAK
#line 1585 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(HEX):
case YY_STATE_EOF(BABYLONIAN):
case YY_STATE_EOF(LINECOMMENT):
case YY_STATE_EOF(BLOCKCOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 243 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 243 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 242);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 181 "lexer.l"


//function to convert babylonian string to decimal number; 1 = Y, 10 = <; base is 60 seperated by space
int babylonian_to_decimal(char* str){
    int num = 0;
    int base = 60;
    int digit = 0;
    int i = 0;

    
    // count number of digits
    while(str[i] != '\0'){
            if(str[i] == ' '){
                    digit++;
            }
            i++;
    }

    // convert to decimal
    i=0;
    while(str[i] != '\0'){
        
        if(str[i] == 'Y'){
                num += 1 * pow(base, digit);
        }
        else if(str[i] == '<'){
                num += 10 * pow(base, digit);
        }
        else if(str[i] == ' '){
                digit--;
        }
        i++;
    }
    return num;
}

void addstr(char ch){
    int l = strlen(str_buf);
    str_buf = realloc(str_buf, l+2);
    str_buf[l] = ch;
    str_buf[l+1] = '\0';
}

void init_str_buf(){
    str_buf = malloc(1);
}

/*
 
int main (void){

    int token;

    yylval.type = malloc(1);
    yylval.id = malloc(1);
    yylval.str = malloc(1);
    yylval.op = malloc(1);

    do{
        token = yylex();
	switch(token){
		case str:
			printf("String: %s\n", yylval.str);
			break;
		case num:
			printf("Number: %d\n", yylval.num);
			break;

		case id:
			printf("Identifier: %s\n", yylval.id);
			break;
		
		case lincom:
			printf("Line Comment: %s\n", yylval.str);
			break;

		case blkcom:
			printf("Block Comment: %s\n", yylval.str);
			break;

		case whitespc:
			printf("Whitespace: %s\n", yylval.str);
			break;

		case type:
			printf("Type: %s\n", yylval.type);
			break;

	}
    } while (token != eoi);
    exit(EXIT_SUCCESS);
}

*/

